# Homework 4

For this assignment, you will be developing an artificial neural network to classify data given in the __[Dry Beans Data Set](https://archive.ics.uci.edu/ml/datasets/Dry+Bean+Dataset#)__. This data set was obtained as a part of a research study by Selcuk University, Turkey, in which a computer vision system was developed to distinguish seven different registered varieties of dry beans with similar features. More details on the study can be found in the following __[research paper](https://www.sciencedirect.com/science/article/pii/S0168169919311573)__. <br>
### **Make sure to use the lecture notebook on an introduction to keras and cross validation located [here](https://colab.research.google.com/drive/1ksEGL7SJ_wutCIyPYx7Loe5EPdOij6dJ?usp=sharing) and [here](https://colab.research.google.com/drive/1C9Mwf1J2ril1Q4l6n2BjQMb8YaFySG5_?usp=sharing)**.

## About the Data Set
Seven different types of dry beans were used in a study in Selcuk University, Turkey, taking into account the features such as form, shape, type, and structure by the market situation. A computer vision system was developed to distinguish seven different registered varieties of dry beans with similar features in order to obtain uniform seed classification. For the **classification** model, images of 13611 grains of 7 different registered dry beans were taken with a high-resolution camera. Bean images obtained by computer vision system were subjected to segmentation and feature extraction stages, and a total of 16 features - 12 dimensions and 4 shape forms - were obtained from the grains.

Number of Instances (records in the data set): __13611__

Number of Attributes (fields within each record, including the class): __17__

### Data Set Attribute Information:

1. __Area (A)__ : The area of a bean zone and the number of pixels within its boundaries.
2. __Perimeter (P)__ : Bean circumference is defined as the length of its border.
3. __Major axis length (L)__ : The distance between the ends of the longest line that can be drawn from a bean.
4. __Minor axis length (l)__ : The longest line that can be drawn from the bean while standing perpendicular to the main axis.
5. __Aspect ratio (K)__ : Defines the relationship between L and l.
6. __Eccentricity (Ec)__ : Eccentricity of the ellipse having the same moments as the region.
7. __Convex area (C)__ : Number of pixels in the smallest convex polygon that can contain the area of a bean seed.
8. __Equivalent diameter (Ed)__ : The diameter of a circle having the same area as a bean seed area.
9. __Extent (Ex)__ : The ratio of the pixels in the bounding box to the bean area.
10. __Solidity (S)__ : Also known as convexity. The ratio of the pixels in the convex shell to those found in beans.
11. __Roundness (R)__ : Calculated with the following formula: (4piA)/(P^2)
12. __Compactness (CO)__ : Measures the roundness of an object: Ed/L
13. __ShapeFactor1 (SF1)__
14. __ShapeFactor2 (SF2)__
15. __ShapeFactor3 (SF3)__
16. __ShapeFactor4 (SF4)__

17. __Classes : *Seker, Barbunya, Bombay, Cali, Dermosan, Horoz, Sira*__

### Libraries that can be used :
- NumPy, SciPy, Pandas, Sci-Kit Learn, TensorFlow, Keras. You may also use PyTorch (though support may be limited)
- Any other library used during the lectures and discussion sessions.

### Other Notes
- Don't worry about not being able to achieve high accuracy, it is neither the goal nor the grading standard of this assignment.
- Discussion and Lecture materials should be helpful for doing the assignments.
- The homework submission should be a .ipynb file.


In [1]:
!git clone https://github.com/ucsd-cse151a-ss25/hw4.git

fatal: destination path 'hw4' already exists and is not an empty directory.


In [10]:
!pip install scikeras
!pip install -U scikit-learn scikeras

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 35.0 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.1
    Uninstalling scikit-learn-1.6.1:
      Successfully uninstalled scikit-learn-1.6.1



## Exercise 1 : Building a Feed-Forward Neural Network(50 points)

### Exercise 1.1 : Data Preprocessing (10 points)

- As the classes are categorical, use one-hot encoding to represent the set of classes. You will find this useful when developing the output layer of the neural network.
- Split the data into training and testing set by __90:10__ and use the training set for training the model and the test set to evaluate the model performance. Please set verbose=0 to suppress output during training.
- Normalize each field of the input data using the min-max normalization technique.

__Notes:__

- Splitting of the dataset should be done __before__ the normalization step and __after__ the one-hot encoding.

In [1]:
# Import Dry_Beans_Dataset.csv
import pandas as pd
import numpy as np
df = pd.read_csv('./hw4/Dry_Beans_Dataset.csv')

df

Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
0       44830    814.955       320.731947       178.405838      1.797766   
1       33476    691.826       258.837971       165.220760      1.566619   
2       27057    606.138       227.460904       151.860320      1.497830   
3       49483    844.283       326.602913       194.689529      1.677558   
4       22461    544.584       192.801303       148.541136      1.297966   
...       ...        ...              ...              ...           ...   
13606   39956    745.166       273.867402       186.564001      1.467954   
13607  171914   1595.676       598.541646       368.358372      1.624889   
13608   48266    817.340       304.682706       202.282198      1.506226   
13609   43279    843.066       336.280446       164.667135      2.042183   
13610   46856    809.173       302.595376       197.920303      1.528875   

       Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
0          0.831018       45297     238.912806  0.658877  0.989690   0.848226   
1          0.769773       33907     206.453305  0.721155  0.987289   0.878921   
2          0.744491       27358     185.607226  0.801831  0.988998   0.925436   
3          0.802907       50289     251.005403  0.680179  0.983973   0.872348   
4          0.637517       22699     169.110122  0.774731  0.989515   0.951720   
...             ...         ...            ...       ...       ...        ...   
13606      0.732079       40504     225.551678  0.796000  0.986470   0.904244   
13607      0.788194      174673     467.854361  0.815980  0.984205   0.848461   
13608      0.747812       48780     247.899536  0.807232  0.989463   0.907916   
13609      0.871907       43813     234.743550  0.614566  0.987812   0.765181   
13610      0.756429       47372     244.251739  0.726900  0.989107   0.899275   

       Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  \
0         0.744899      0.007154      0.001359      0.554874      0.997534   
1         0.797616      0.007732      0.001930      0.636191      0.996669   
2         0.815996      0.008407      0.002299      0.665850      0.997330   
3         0.768534      0.006600      0.001420      0.590644      0.990840   
4         0.877121      0.008584      0.003134      0.769342      0.998579   
...            ...           ...           ...           ...           ...   
13606     0.823580      0.006854      0.001945      0.678284      0.995690   
13607     0.781657      0.003482      0.000802      0.610988      0.992788   
13608     0.813632      0.006313      0.001706      0.661997      0.997117   
13609     0.698059      0.007770      0.001138      0.487286      0.995128   
13610     0.807189      0.006458      0.001691      0.651555      0.996145   

          Class  
0          SIRA  
1      DERMASON  
2      DERMASON  
3          SIRA  
4      DERMASON  
...         ...  
13606  DERMASON  
13607    BOMBAY  
13608      SIRA  
13609     HOROZ  
13610      SIRA  

[13611 rows x 17 columns]

In [2]:
from sklearn.model_selection import train_test_split

# Use one-hot encoding to represent the set of classes
y = pd.get_dummies(df["Class"], dtype=int)
X = df.drop(columns=["Class"])

# Split data into training and testing set by 90:10
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

# Normalize each field of the input data using the min-max nomalization technique
X_min = X_train.min()
X_max = X_train.max()
X_train = (X_train - X_min) / (X_max - X_min)
X_test = (X_test - X_min) / (X_max - X_min)

### Exercise 1.2 : Training and Testing the Neural Network (40 points)

Design a 3-layer (3 hidden layers and this does not include the input or output layer) artificial deep neural network, specifically a feed-forward multi-layer perceptron (using the sigmoid activation function), to classify the type of 'Dry Bean' given the other attributes in the data set, similar to the one mentioned in the paper above. Please note that this is a **multi-class classification** problem so select the right number of nodes accordingly for the input and output layers.

Consider the following hyperparameters while developing your model:

- Model type: Keras Sequential
- Make sure your input layer matches the size of your X matrix
- Number and type of hidden layers: 3 and Dense
- Number of nodes in each hidden layer: 12
- Learning rate should be 0.3
- Number of epochs should be 100
- The sigmoid function is to be used as the activation function in each layer
- Your output layer has to use a sigmoid function and the number of outputs should match the shape of your y
- Your loss function should be MSE
- Stochastic Gradient Descent should be used to minimize the error rate

**Note:** We are having you use MSE as your loss function for this model, is this a good choice? Why or why not? If not, what should you use instead in future models? Answer below

__Requirements once the model has been trained :__

- A confusion matrix for all classes, specifying the true positive, true negative, false positive, and false negative cases for each category in the class
- Since we do have OHE output (multi-class output) you will need to either reshape or argmax your outputs. Make sure they have already been thresholded as well i.e. look at yhat and do you see 1's and 0's?
- The accuracy and mean squared error (MSE) of the model
- The precision and recall for each label in the class

__Notes :__

- The mean squared error (MSE) values obtained __should be positive__.


In [3]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD

classifier = Sequential() # Initialising the ANN

num_features = X_train.shape[1]

# Hidden Layers
classifier.add(Dense(units = 12, activation = 'sigmoid', input_dim = num_features)) # here our input dimension is set to 9 via the input_dim parameter for our first hidden layer
classifier.add(Dense(units = 12, activation = 'sigmoid'))
classifier.add(Dense(units = 12, activation = 'sigmoid'))

num_classes = y_train.shape[1]

# Output Layer
classifier.add(Dense(units = num_classes, activation = 'sigmoid'))

# SGD Learning rate 0.3
optim = SGD(learning_rate=0.3)
classifier.compile(optimizer=optim, loss='mse', metrics=['mse'])

classifier.summary()

# Training
history = classifier.fit(X_train.astype(float), y_train, batch_size = 64, epochs = 100)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 12)             │           204 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 12)             │           156 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 12)             │           156 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 7)              │            91 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 607 (2.37 KB)

 Trainable params: 607 (2.37 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 0.1725 - mse: 0.1725
Epoch 2/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 0.1188 - mse: 0.1188
Epoch 3/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.1185 - mse: 0.1185
Epoch 4/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.1183 - mse: 0.1183
Epoch 5/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1178 - mse: 0.1178
Epoch 6/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.1179 - mse: 0.1179
Epoch 7/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.1181 - mse: 0.1181
Epoch 8/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.1181 - mse: 0.1181
Epoch 9/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1180 - mse: 0.1180
Epoch 10/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1183 - mse: 0.1183
Epoch 11/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1180 - mse: 0.1180
Epoch 12/100
192/192 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1181 - mse: 0.1181
Epoch 13/10

In [4]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

# Test Set Prediction
yhat_test = classifier.predict(X_test.astype(float))

# Argmax outputs
yhat_test_reshaped = np.argmax(yhat_test, axis=1)
y_test_reshaped = np.argmax(y_test, axis=1)

# Confusion Matrix
cm = confusion_matrix(y_test_reshaped, yhat_test_reshaped)
print(cm)

# Calc Accuracy and MSE of model
print("Accuracy: " + str(accuracy_score(y_test_reshaped, yhat_test_reshaped)))

# tuple index out of range error
num_classes = yhat_test.shape[1]
y_test_OH = np.eye(num_classes)[y_test_reshaped]

print("MSE: " + str(classifier.evaluate(X_test.astype(float), y_test_OH.astype(float))[0]))

# Calc Precision and Recall for each label in class
print(classification_report(y_test_reshaped,yhat_test_reshaped))

43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
[[  0   0   0 137   0   0   0]
 [  0   0   0  63   0   0   0]
 [  0   0   0 195   0   0   0]
 [  0   0   0 342   0   0   0]
 [  0   0   0 181   0   0   0]
 [  0   0   0 200   0   0   0]
 [  0   0   0 244   0   0   0]]
Accuracy: 0.2511013215859031
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1198 - mse: 0.1198
MSE: 0.11900778859853745
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       137
           1       0.00      0.00      0.00        63
           2       0.00      0.00      0.00       195
           3       0.25      1.00      0.40       342
           4       0.00      0.00      0.00       181
           5       0.00      0.00      0.00       200
           6       0.00      0.00      0.00       244

    accuracy                           0.25      1362
   macro avg       0.04      0.14      0.06      1362
weighted avg       0.06      0.25      0.10      1362



/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


**We are having you use MSE as your loss function for this model, is this a good choice? Why or why not? If not, what should you use instead in future models?**

Per the class lecture, MSE is not a good loss function for this model. MSE is mostly used for regression problems because it is a distance measurement. But we are using this model for classification. We also have many one-hot values, which are not continuous. From the outputs I got in using MSE, it's obvious this model did very poor. Instead, something like cross entropy would be better as it's used to compare probabilities between predicted and true values.

## Exercise 2 : k-fold Cross Validation (20 points)

In order to avoid **using biased models**, use 10-fold cross validation to generalize the model from Ex1.2 on the given data set. You can choose a n_repeats value of 1-5

__Requirements :__
- Print the accuracy values during each iteration of the **cross validation** not the iterations per epoch or the epochs
- Print the overall average accuracy per each n_fold value, look at the documentation for the scoring parameter



In [9]:
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import cross_val_score

def buildmodel():
    model = Sequential([
        Dense(12, activation = 'sigmoid', input_dim = X.shape[1]), # Here our input dimension is set inside the first hidden layer with input_dim = X.shape[1]
        Dense(12, activation = 'sigmoid'),
        Dense(12, activation = 'sigmoid'),
        Dense(y.shape[1], activation = 'sigmoid')
    ])
    optim = SGD(learning_rate=0.3)
    model.compile(optimizer=optim, loss='mse', metrics=['mse'])
    return model

estimator = KerasClassifier(model=buildmodel, epochs=100, batch_size=64, verbose = 0) # before submitting please set verbose = 0, and rerun. If not grading will be no bueno!
kfold = RepeatedKFold(n_splits = 10, n_repeats = 1)
results = cross_val_score(estimator, X_train, y_train, cv=kfold, n_jobs = 1)  # 1 cpus

print("Each fold accuracy\n", results)
print("Overall accuracy\n", np.mean(results))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/lo

Each fold accuracy
 [0.25959184 0.24653061 0.3844898  0.25795918 0.26367347 0.27428571
 0.28326531 0.26938776 0.24326531 0.25816993]
Overall accuracy
 0.2740618914232359


## Exercise 3 : Hyperparameter Tuning (25 points)

Use either grid search or random search methodology to find the optimal number of nodes required in each hidden layer, as well as the optimal learning rate and the different activation functions or optimization approaches, [keras_tuner examples](https://keras.io/guides/keras_tuner/getting_started/) such that the accuracy of the model is maximum for the given data set.

__Requirements :__
- The set of optimal hyperparameters
- Try your best to maximize accuracy using this set of optimal hyperparameters

__Note :__ Hyperparameter tuning takes a lot of time to execute. Make sure that you choose the appropriate number of each hyperparameter (preferably 3 of each), and that you allocate enough time to execute your code. Make sure to tune at least three parameters with three options each at a minimum, but feel free to experiment with more, just recognize that it will grow exponentially in running time

In [10]:
!pip install keras_tuner -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.1/129.1 kB 2.2 MB/s eta 0:00:00


In [ ]:
import keras_tuner

num_features = X_train.shape[1]
num_classes = y_train.shape[1]

def buildHPmodel(hp):
  model= Sequential([
      Dense(
              # Tune number of units.
              units=hp.Int("units1", min_value=12, max_value=64, step=8),
              # Tune the activation function to use.
              activation=hp.Choice("activation1", ["sigmoid", "tanh", "relu"]),
              input_dim=num_features
      ),
      Dense(
              # Tune number of units.
              units=hp.Int("units2", min_value=12, max_value=64, step=8),
              # Tune the activation function to use.
              activation=hp.Choice("activation2", ["sigmoid", "tanh", "relu"]),
      ),
      Dense(
              # Tune number of units.
              units=hp.Int("units3", min_value=12, max_value=64, step=8),
              # Tune the activation function to use.
              activation=hp.Choice("activation3", ["sigmoid", "tanh", "relu"]),
      ),
      Dense(num_classes, activation="sigmoid")
])

  learning_rate = hp.Float("lr", min_value=1e-4, max_value=1e-2, sampling="log")
  model.compile(optimizer=SGD(learning_rate=learning_rate), loss='mse', metrics=['mse', 'accuracy'])
  return model

tuner = keras_tuner.GridSearch(
    hypermodel=buildHPmodel,
    objective="val_accuracy",
    max_trials=20,
    executions_per_trial=1,
    tune_new_entries=True,
    allow_new_entries=True,
    max_consecutive_failed_trials=3
)

tuner.search_space_summary()

# Here we partition our data for Training and Testing
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, random_state = 0)

tuner.search(X_train, y_train, epochs=2, validation_data=(X_val, y_val))

tuner.results_summary()

models = tuner.get_best_models(num_models=1)
models[0].summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Search space summary
Default search space size: 7
units1 (Int)
{'default': None, 'conditions': [], 'min_value': 12, 'max_value': 64, 'step': 8, 'sampling': 'linear'}
activation1 (Choice)
{'default': 'sigmoid', 'conditions': [], 'values': ['sigmoid', 'tanh', 'relu'], 'ordered': False}
units2 (Int)
{'default': None, 'conditions': [], 'min_value': 12, 'max_value': 64, 'step': 8, 'sampling': 'linear'}
activation2 (Choice)
{'default': 'sigmoid', 'conditions': [], 'values': ['sigmoid', 'tanh', 'relu'], 'ordered': False}
units3 (Int)
{'default': None, 'conditions': [], 'min_value': 12, 'max_value': 64, 'step': 8, 'sampling': 'linear'}
activation3 (Choice)
{'default': 'sigmoid', 'conditions': [], 'values': ['sigmoid', 'tanh', 'relu'], 'ordered': False}
lr (Float)
{'default': 0.0001, 'conditions': [], 'min_value': 0.0001, 'max_value': 0.01, 'step': None, 'sampling': 'log'}

Search: Running Trial #1

Value             |Best Value So Far |Hyperparameter
12                |12                |units

## Exercise 4 - Collaborative Statement (5 points)

It is mandatory to include a Statement of Collaboration in each submission, that follows the guidelines below.
Include the names of everyone involved in the discussions (especially in-person ones), and what was discussed.
All students are required to follow the academic honesty guidelines posted on the course website. For
programming assignments in particular, I encourage students to organize (perhaps using Piazza) to discuss the
task descriptions, requirements, possible bugs in the support code, and the relevant technical content before they
start working on it. However, you should not discuss the specific solutions, and as a guiding principle, you are
not allowed to take anything written or drawn away from these discussions (no photographs of the blackboard,
written notes, referring to Piazza, etc.). Especially after you have started working on the assignment, try to restrict
the discussion to Piazza as much as possible, so that there is no doubt as to the extent of your collaboration.

Even if you did not use any outside resources or collaborate with anyone, please state that explicitly in the space below.

I did not collaborate with anyone and used only the documentation and notebooks given in this assignment.